language: node_js

node_js:
  - 'node'
  - 'lts/*'

script:
  - npm test -- --maxWorkers=4

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
